# This is an example file
# Adjust it for your project's needs
application:
    build: bigsoda/symfony-app
    volumes:
        - symfony:/var/www/symfony
    tty: true
db:
    image: mysql/mysql-server:5.6
    ports:
        - "6306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: "root"
        MYSQL_DATABASE: "symfony"
        MYSQL_USER: "symfonyuser"
        MYSQL_PASSWORD: "symfonypass"
php:
    build: bigsoda/symfony-php-fpm
    ports:
        - "6022:22"
    expose:
        - 9000:9000
    volumes_from:
        - application
    links:
        - db
nginx:
    build: bigsoda/symfony-nginx
    ports:
        - "6080:80"
    links:
        - php
    volumes_from:
        - application
